# Site settings
title: Winter Pi Blog
SEOTitle: Winter Pi 的博客 | Blog
# header-img: img/home-bg.jpg
# email: huxpro@gmail.com
description: "这里是 皮冰锋 的个人博客 | 作为一个程序妈"
# keyword: "黄玄, Hux黄玄, Hux, 鬼栈, huxpro, @huxpro, 黄玄的博客, Hux Blog, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"


remote_theme: sighingnow/jekyll-gitbook

# https://github.com/gitalk/gitalk#install
gitalk:
  owner: winterpi
  repo: blog-comments
  clientID: b902c4150c01b5ab9bb4
  clientSecret: bbe8efb3af10421a83734f8ddde4133fce283490
