remote_theme: sighingnow/jekyll-gitbook
#toc:
#    enabled: true

# url: 'https://github.com/winterpi/blog'

url: 'https://github.com/winterpi'
baseurl:  '/blog'

# disqushandler: "皮皮"

# https://github.com/gitalk/gitalk#install
gitalk:
  owner: winterpi
  repo: blog-comments
  clientID: b902c4150c01b5ab9bb4
  clientSecret: bbe8efb3af10421a83734f8ddde4133fce283490
